#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -10 -yoffset -40 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 3 <<< "> Logout|> Reboot|> Shutdown")"
            case "$MENU" in
                *Logout) exec i3-msg exit ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
